services:
  symfony:
    build: .
    container_name: symfony
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html
    environment:
      DATABASE_URL: "postgresql://symfony:secret@db:5432/symfony?sslmode=disable&serverVersion=15&charset=utf8"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony -d symfony"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  redis:
    container_name: redis
    image: redis
    ports: ["6379:6379"]
    networks:
      - app-network
  rabbitmq:
    container_name: rmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network
volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge
