parameters:
  person_uploads: "%kernel.project_dir%/public/uploads/person"
  film_uploads: "%kernel.project_dir%/public/uploads/films"
  user_uploads: "%kernel.project_dir%/public/uploads/user"
  uploads_dir: "%kernel.project_dir%/public/uploads"
  public_dir: "%kernel.project_dir%/public"
  app_url: "%env(APP_URL)%"
  app_domain: "%env(APP_DOMAIN)%"
  password_reset_url: "%env(PASSWORD_RESET_URL)%"
  image_service_url: "%env(IMAGE_SERVICE_URL)%"
  elasticsearch.hosts: ["%env(ELASTIC_SEARCH_URL)%"]
services:
  gedmo.listener.timestampable:
    class: Gedmo\Timestampable\TimestampableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [setAnnotationReader, ["@annotation_reader"]]
  Elastic\Elasticsearch\Client:
    factory: ['Elastic\Elasticsearch\ClientBuilder', "fromConfig"]
    arguments:
      - hosts: "%elasticsearch.hosts%"
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
  App\Service\FileSystemService:
    arguments:
      - "@slugger"
  App\EventListener\FilmListener:
    tags:
      - {
          name: doctrine.orm.entity_listener,
          entity: App\Entity\Film,
          event: prePersist,
        }
      - {
          name: doctrine.orm.entity_listener,
          entity: App\Entity\Film,
          event: preUpdate,
        }
    arguments:
      $slugger: '@Symfony\Component\String\Slugger\SluggerInterface'
  App\EventListener\PersonListener:
    tags:
      - {
          name: doctrine.orm.entity_listener,
          entity: App\Entity\Person,
          event: prePersist,
        }
      - {
          name: doctrine.orm.entity_listener,
          entity: App\Entity\Person,
          event: preUpdate,
        }
    arguments:
      $slugger: '@Symfony\Component\String\Slugger\SluggerInterface'
